# Generated by Django 3.2.9 on 2021-12-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant.category')),
                ('manager_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.manager')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='foodimg')),
                ('discreption', models.TextField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('delivery_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('order', 'order'), ('order_registration', 'order_registration'), ('Send', 'Send'), ('Delivery', 'Delivery')], default='order_registration', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.department')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.department')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('food_id', models.ManyToManyField(to='restaurant.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('number', models.IntegerField()),
                ('Food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.food')),
                ('Menu_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.menu')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='menu_id',
            field=models.ManyToManyField(related_name='menu', through='restaurant.Food_Menu', to='restaurant.Menu'),
        ),
    ]
