# Generated by Django 3.2.9 on 2022-01-12 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_adress_owner'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='branchimg'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer1', to='accounts.customer'),
        ),
    ]
