# Generated by Django 3.2.9 on 2022-01-13 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20220112_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department1', to='restaurant.department'),
        ),
    ]
