# Generated by Django 3.2.9 on 2021-12-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='plaque',
            field=models.IntegerField(),
        ),
    ]
