# Generated by Django 3.2.9 on 2022-01-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_adress_plaque'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_adress', models.BooleanField(default=False)),
                ('address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adress_related', to='accounts.adress')),
            ],
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'superuser', 'verbose_name_plural': 'superusers'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'restaurant-manager', 'verbose_name_plural': 'resurants_managers'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_id',
        ),
        migrations.AddField(
            model_name='customeradress',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='adress_id',
            field=models.ManyToManyField(related_name='customeradress', through='accounts.CustomerAdress', to='accounts.Adress'),
        ),
    ]
