# Generated by Django 3.2.9 on 2022-01-09 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220106_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='adress_id',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='customeradress',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='customeradress',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='customeradress',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer2', to='accounts.customer'),
        ),
    ]
